# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phd-tools"
version = "0.0.1"
description = "Convenience tools for my phd research and final thesis"
readme = "README.md"
authors = [{ name = "Andrew Mueller", email = "andrewstermueller@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["phd", "thesis", "caltech", "tools"]
dependencies = [
    "numpy",
    "matplotlib",
    "orjson",
    "scipy",
    "bokeh",
    "numba",
    "ipython",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["black"]

[project.urls]
Homepage = "https://github.com/realpython/reader"

[project.scripts]
phdtools = "reader.__main__:main"